"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import { useState } from "react";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [open, setOpen] = useState(false);
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="overflow-x-hidden bg-[linear-gradient(to_bottom_right,_#EFF2F3_0%,_#EAFAFF_40%,_white_100%)] antialiased"
      >

        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
        <footer className="w-full py-2">
          <div className="mx-auto p-[10px] md:p-[50px] flex flex-col md:flex-row items-center justify-between text-sm">

            {/* Left copyright */}
            <span className="text-gray-700 order-2 md:order-1 pt-[5px] md:pt-0">© 2024 Warmonks</span>

            {/* Right links */}
            <div className="hidden md:flex  items-center gap-10 text-gray-700 order-1 md:order-2">
              <a href="#" className="hover:underline">Terms & Conditions</a>
              <a href="#" className="hover:underline">Privacy Policy</a>
              <a href="#" className="hover:underline">About</a>
              <a href="#" className="hover:underline">Blog</a>
              <a href="#" className="hover:underline">Contact</a>
            </div>
            <div className="bg-gradient-to-b from-[#EAF6FF] to-white flex flex-col gap-5 md:hidden border border-gray-300 rounded-lg p-4 w-full">
              {open && (
                <ul className="mt-8 mb-8 flex flex-col gap-3 text-center">
                  <li className="cursor-pointer hover:opacity-75">Terms & Conditions</li>
                  <li className="cursor-pointer hover:opacity-75">Privacy Policy</li>
                  <li className="cursor-pointer hover:opacity-75">About</li>
                  <li className="cursor-pointer hover:opacity-75">Blog</li>
                  <li className="cursor-pointer hover:opacity-75">Contact</li>
                </ul>
              )}
              <button
                onClick={() => setOpen(!open)}
                className="w-full text-left font-semibold flex justify-between"
              >
                Quick Links
                <span>{open ? "▲" : "▼"}</span>
              </button>
            </div>

          </div>
        </footer>

      </body>
    </html>
  );
}
